{% set name = "falcon" %}
{% set version = "3.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23335dbccd44f29e85ec55f2f35d5a0bc12bd7a509f641ab81f5c64b65626263

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - falcon-bench = falcon.cmd.bench:main
    - falcon-print-routes = falcon.cmd.inspect_app:route_main
    - falcon-inspect-app = falcon.cmd.inspect_app:main
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python

test:
  imports:
    - falcon
    - falcon.cmd
    - falcon.media
    - falcon.routing
    - falcon.testing
    - falcon.util
    - falcon.asgi
  requires:
    - pip
  commands:
    - falcon-bench -h
    - falcon-print-routes -h
    - falcon-inspect-app -h
    - pip check

about:
  home: http://falconframework.org
  license: Apache-2.0
  license_file: LICENSE
  summary: An unladen web framework for building APIs and app backends.
  description: |
    Falcon is a high-performance Python framework for building cloud APIs. It
    encourages the REST architectural style, and tries to do as little as
    possible while remaining highly effective.
  doc_url: http://falcon.readthedocs.io/en/stable/
  dev_url: https://github.com/falconry/falcon/

extra:
  recipe-maintainers:
    - daf
    - synapticarbors
    - carlodri
